version: '3.8'

services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yet-docs
    environment:
      - VIRTUAL_HOST=api-docs.yet-kenya.com
      - LETSENCRYPT_HOST=api-docs.yet-kenya.com
      - LETSENCRYPT_EMAIL=brian@hudumacitypay.com
    expose:
      - "80"
    networks:
      - proxy

networks:
  proxy:
    external: true
